function fig = lprf_req_driver()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load lprf_req_driver

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','C:\RSA\chap1\programs1\lprf_req_driver.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[423 149 560 564], ...
	'ResizeFcn','legend(''ResizeLegend'')', ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[18.75 110.25 74.25 19.5], ...
	'String','frequency - HZ', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','freq = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[91.5 111 45 18.75], ...
	'String','5.6e9', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','g = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[92.25 78 45 18.75], ...
	'String','45', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[18.75 76.5 74.25 19.5], ...
	'String','antenna gain - dB', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','sigma = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[93 43.5 45 18.75], ...
	'String','0.1', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[18 43.5 74.25 19.5], ...
	'String','RCS- meter squared', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat1, ...
	'ListboxTop',0, ...
	'Position',[93.75 12.75 45 18.75], ...
	'String','290', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[18.75 11.25 74.25 19.5], ...
	'String','Te - kelvin', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','nf = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[225.75 111.75 45 18.75], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[150.75 111.75 74.25 19.5], ...
	'String','noise figure - dB', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[150.75 75 74.25 19.5], ...
	'String','losses - dB', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','loss = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[225.75 75.75 45 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[150 41.25 74.25 19.5], ...
	'String','range - Km', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','range = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[225 42 45 18.75], ...
	'String','86', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[151.5 12 74.25 19.5], ...
	'String','PRF - Hz', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','prf = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[225.75 13.5 45 18.75], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','pt_percent=str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[363 10.5 45 18.75], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[289.5 10.5 74.25 19.5], ...
	'String','pt_ percent', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','rcs_delta = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[365.25 42 45 18.75], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[291 42 74.25 19.5], ...
	'String','RCS delta - dB', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','np2 = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[365.25 75 45 18.75], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[291 75 74.25 19.5], ...
	'String','np2', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[292.5 111.75 74.25 19.5], ...
	'String','np1', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','np1 = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[365.25 108.75 45 18.75], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',mat2, ...
	'ListboxTop',0, ...
	'Position',[356.25 354 55.5 19.5], ...
	'String','Go', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close all', ...
	'ListboxTop',0, ...
	'Position',[356.25 317.25 55.5 19.5], ...
	'String','Quit', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','np = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[364.5 141 45 18.75], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[289.5 141 74.25 19.5], ...
	'String','# of pulses, np', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[149.25 141 74.25 19.5], ...
	'String','bandwidth - Hz', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','b = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[223.5 141 45 18.75], ...
	'String','5e6', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','pt = str2num(get(gco,''string''));', ...
	'ListboxTop',0, ...
	'Position',[92.25 138.75 45 18.75], ...
	'String','1.5e6', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[17.25 139.5 74.25 19.5], ...
	'String','peak power - KW', ...
	'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
